# Colors (Everforest Dark)

# Default colors
[colors.primary]
background = '#272e33'
# Darker variant with https://mdigi.tools/darken-color
# background = '#23292e'
# My experiments
# background = '#3a3735'
# background = '#35352d'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
# blue    = '#7fbbb3'
# Darkened version, 10%, visibiilty with lscolors is too low
blue    = '#6ab0a7'
# Darkened version, 20%
# blue    = '#57a49a'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors (same as normal colors, might be a problem)
[colors.bright]
# Changed this   to make autosuggestions legible
# I looked at the palletes on https://github.com/sainnhe/everforest and picked
black   = '#859289'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

