#!/bin/bash
LINK="https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
if sh -c "$(curl -fsSL $LINK)" || sh -c "$(wget -O- $LINK)"; then
    echo "Successfully installed oh-my-zsh."
    echo "Copying themes..."
    ln -sf "$HOME/dotfiles/custom.zsh-theme" "$HOME/.oh-my-zsh/themes"
else
    STATUS=$?
    echo "Failed to install oh-my-zsh"
    exit $STATUS
fi
