# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent
# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=~/.config/i3/i3blocks/$BLOCK_NAME
separator_block_width=20
separator=false
align=center

# Find your own networking interfaces by typing
# 'ip link' or 'ifconfig' in a terminal window.
# Yours are probably different than mine!

#my ethernet interface is eno1
# most people's is eth0
[bandwidth]
instance=enp5s0
interval=5
color=#dfa000
label= 

#my wifi interface is wlan0
[wifi]
instance=wlan0
interval=10
color=#dfa000
label= 

# this was able to not show wifi when it wasn't the main interface
# remove bandwidth part from wifi script and activate this
#[bandwidth]
#instance=wlp4s0
#interval=5
#color=#fb4934

########################
separator_block_width=20
[spacer]
separator_block_width=20
full_text=
color=#df69ba
########################

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
label= 
interval=30
color=#8da101

########################
separator_block_width=20
[spacer]
separator_block_width=20
full_text=
color=#df69ba
########################



# Disk usage
#
# The directory defaults to $HOME if the instance is not specified.
# The script may be called with a optional argument to set the alert
# (defaults to 10 for 10%).
[disk]
label= 
interval=30
color=#f85552
separator_block_width=20

# my root / partition
[disk]
label=/ 
instance=/dev/nvme0n1p9
interval=60
color=#f85552


########################
separator_block_width=20
[spacer]
separator_block_width=20
full_text=
color=#df69ba
########################


# Battery indicator
[battery]
interval=30
min_width= 100%
align=center
color=#dfa000


########################
separator_block_width=20
[spacer]
separator_block_width=20
full_text=
color=#df69ba
########################

# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[cpu_usage]
label= 
interval=10
min_width= 100.00%
color=#8da101

########################
separator_block_width=20
[spacer]
separator_block_width=20
full_text=
color=#df69ba
########################



[date]
command=date +"%a, %d.%m. %H:%M:%S"
interval=1 
label= 
color=#f85552

########################
separator_block_width=20
[spacer]
full_text= 
color=#df69ba
########################


#red #f85552
#green #8da101
#yellow #dfa000
#blue #7fbbb3
#purple #df69ba
#aqua #83c092
#

