#!/bin/bash
# TODO: deprecate oh-my-zsh and this file
LINK="https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
ZSH_PATH="$HOME/.config/oh-my-zsh"

rm -rf $ZSH_PATH

# had problems with wget (check file history if you want to bring it back)
if which curl && ZSH=$ZSH_PATH sh -c "$(curl -fsSL $LINK  | sed -E 's/\.git\}/}/')"; then
    echo "Successfully installed oh-my-zsh."
else
    STATUS=$?
    echo "Failed to install oh-my-zsh"
    exit $STATUS
fi
