#!/bin/bash
# TODO: deprecate oh-my-zsh and this file
LINK="https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
if sh -c "$(curl -fsSL $LINK  | sed -E 's/\.git\}/}/')" || sh -c "$(wget -O- $LINK)"; then
    echo "Successfully installed oh-my-zsh."
else
    STATUS=$?
    echo "Failed to install oh-my-zsh"
    exit $STATUS
fi
