# Everforest light

# Dim inactive windows

# Everforest ligth hard - comment out when lecturing
setw -g window-active-style bg=#fffbef
setw -g window-style bg=#f2efdf

# Gruvbox light uncomment when lecturing for better contrast
# setw -g window-active-style bg=#fbf1c7
# setw -g window-style bg=#f2e5bc
