#!/bin/zsh
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
HOME=~

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="custom"
# Someday, I'll replace the theme
# . "$ZDOTDIR/theme.zsh"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git zsh-autosuggestions)

# Start replacing oh-my-zsh, this loads the plugins plugin
. "$ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
# too colorful for my taste
# . "$ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

source "$ZSH/oh-my-zsh.sh"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [ -f "$XDG_CONFIG_HOME/shell/aliases" ]; then
    . "$XDG_CONFIG_HOME/shell/aliases"
fi

# Set Fuzzy Finder path depending on OS
if [ -d "/usr/share/fzf" ]; then
    FZF_PATH='/usr/share/fzf'
elif [ -d '/opt/homebrew/opt/fzf/shell/' ]; then
    FZF_PATH='/opt/homebrew/opt/fzf/shell'
fi

# Configure Fuzzy Finder
if [ ! -z "$FZF_PATH" ]; then
    [[ $- == *i* ]] && . "${FZF_PATH}/completion.zsh" 2> /dev/null
    . "${FZF_PATH}/key-bindings.zsh"
    export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
    export FZF_CTRL_T_OPTS="--preview 'highlight --out-format=ansi {}'" 
    # Uncomment to preview files using bat 
    # export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always --line-range :500 {}'"
    export FZF_COMPLETION_TRIGGER='**'
fi

if [[ ! $COLORTERM =~ ^(truecolor|24bit)$ ]]; then
    # if we're dealing with a terminal not supporting trucolors (e.g., urxvt),
    # then execute a script overriding the terminal's color defaults to enable
    # gruvbox theme in vim found.
    source "$HOME/.vim/plugged/gruvbox/gruvbox_256palette.sh"
fi

test -e /Users/sodic/.config/zsh/.iterm2_shell_integration.zsh && source /Users/sodic/.config/zsh/.iterm2_shell_integration.zsh || true

# Toggle between built-in-display and external monitory
toggle-display () {
    config_files=("Xresources" "rofi/config.rasi" "shell/env")
    prefix="$HOME/dotfiles"
    variant="$1"
    for link in "${config_files[@]}"; do
        rm "$prefix/$link"
        ln -s "$prefix/$link.$variant" "$prefix/$link"
    done
}
