#!/bin/bash

# This file is executed by bash login shells

# The home path is hardcoded because we can't rely on having XDG variables
# already set (i.e., .profile is the one that eventually sets them).
if [ -f "$HOME/.profile" ]; then
    source "$HOME/.profile"
fi

# Shells that execute .bash_profile won't execute .bashrc (I guess?)
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

